Loggin ini
plone/plone.recipe.zope2instance pull request #196
Opened 2024-09-05 10:11 UTC by Sakoes

2024-09-05 10:11 UTC, mister-roboto commented
@Sakoes you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2024-09-05 12:54 UTC, gotcha requested changes
You also need to add a CHANGELOG item.

2024-09-05 12:54 UTC, gotcha commented on src/plone/recipe/zope2instance/recipe.py
> +        # Load wsgi template or use default
```suggestion
        # Load wsgi template from file or use global var as default
```

2024-09-05 12:54 UTC, gotcha commented on src/plone/recipe/zope2instance/recipe.py
> +        # Load logging template or use default
```suggestion
        # Load wsgi logging template from file or use global var as default
```

2024-09-05 12:54 UTC, gotcha commented on src/plone/recipe/zope2instance/recipe.py
> +        configparser.ConfigParser().read_file(io.StringIO(wsgi_ini))
```suggestion
        configparser.ConfigParser().read_string(wsgi_ini)
```

Did you try this ?

2024-09-05 12:54 UTC, gotcha commented on src/plone/recipe/zope2instance/recipe.py
> +        logging_ini_template_path = self.options.get("logging-ini-template")
```suggestion
        wsgi_logging_ini_template_path = self.options.get("wsgi-logging-ini-template")
```

I would be more specific.

2024-09-05 12:54 UTC, gotcha commented on src/plone/recipe/zope2instance/recipe.py
> +        if logging_ini_template_path:
```suggestion
        if wsgi_logging_ini_template_path:
```

2024-09-05 12:54 UTC, gotcha commented on src/plone/recipe/zope2instance/recipe.py
> +                with open(logging_ini_template_path) as fp:
```suggestion
                with open(wsgi_logging_ini_template_path) as fp:
```

2024-09-05 12:54 UTC, gotcha commented on src/plone/recipe/zope2instance/recipe.py
> +                    logging_ini_template = fp.read()
```suggestion
                    wsgi_logging_ini_template = fp.read()
```

2024-09-05 12:54 UTC, gotcha commented on src/plone/recipe/zope2instance/recipe.py
> +        wsgi_ini_template += logging_ini_template
```suggestion
        wsgi_ini_template += wsgi_logging_ini_template
```

2024-09-05 13:47 UTC, Sakoes commented on src/plone/recipe/zope2instance/recipe.py
> +        configparser.ConfigParser().read_file(io.StringIO(wsgi_ini))
Tested and implemented with read_string

2024-09-11 09:06 UTC, Sakoes commented
Added changes to news/59.feature

2024-09-16 11:29 UTC, gotcha requested changes
Can you add the new config in the README ?

Did you check you did not break the test suite ?

2024-09-16 11:29 UTC, gotcha commented on src/plone/recipe/zope2instance/recipe.py
> +            wsgi_ini_template += wsgi_logging_ini_template
Can you beautify this and line 946 that read exactly the same ? (As discussed in flesh.)

2024-09-19 08:23 UTC, gotcha requested changes
Mostly cosmetics

2024-09-19 08:23 UTC, gotcha commented on README.rst
> +  By default `plone.recipe.zope2instances` uses a hard-coded logging template for the
```suggestion
  By default `plone.recipe.zope2instance` uses a hard-coded logging template for the
```

Typo

2024-09-19 08:23 UTC, gotcha commented on src/plone/recipe/zope2instance/recipe.py
> +        # Parse wsgi.ini
```suggestion
        # Catch errors in generated wsgi.ini by parsing it before writing the file.```

2024-09-19 08:23 UTC, gotcha commented on README.rst
> +  This option cannot be used togehter with the wsgi-ini-template option (see Advanced options: wsgi-ini-template)
```suggestion
  This option cannot be used together with the wsgi-ini-template option (see Advanced options: wsgi-ini-template)
```

2024-09-19 14:51 UTC, gotcha approved these changes

2024-09-19 14:52 UTC, merged

2024-09-20 06:43 UTC, petschki commented
Hi, tests buildout.coredev are broken since this change ... see https://github.com/plone/buildout.coredev/actions/runs/10943504713/job/30383093298 

```
configparser.DuplicateSectionError: While reading from '<string>' [line 102]: section 'loggers' already exists
```

do we have to change something there or is this change causing it?

2024-09-20 09:13 UTC, petschki commented on src/plone/recipe/zope2instance/recipe.py
> +            wsgi_ini_template += wsgi_logging_ini_template
This is a problem if you have multiple buildout parts with this recipe. the template string gets multiplied every time the recipe is called. I'll prep a fix for that.